# Generated by Django 5.1.2 on 2025-04-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_question_correct_answer_question_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
